mod alternating_case;
mod basic_mathematical_operations;
mod calculate_bmi;
mod convert_to_a_string_to_a_number;
mod count_of_positives_sum_of_negatives;
mod difference_of_volumes_of_cuboids;
mod fake_binary;
mod how_many_lightsabers_do_you_own;
mod opposites_attract;
mod parse_nice_int_from_char_problem;
mod safen_user_input_part_I;
mod simple_multiplication;
mod squaring_an_argument;
mod string_repeat;
mod third_angle_of_a_triangle;
mod what_is_between;
mod will_you_make_it;
mod you_cant_code_under_pressure_1;
fn main() {}
